### PR TITLE
Fixed misspellings

### PR DESCRIPTION
**Pull request by TomasRoj**
I found and fixed some misspellings. Hope you will be okay with this!

### CODE REVIEW

**Comment by tronicgr** [comment]
Yes, you are welcome.

**Review by tronicgr — APPROVED** [review]

**Comment by TomasRoj** [comment]
thanks. then you can merge this!

**Comment by tronicgr** [comment]
Sorry to ask, just a bit new to github, how do you merge?

**Comment by TomasRoj** [comment]
No worry bro! I can teach you! You should see a merge button somewhere under this message.

**Comment by tronicgr** [comment]
lol... just realized this is not my depository. I did write a driver for the Max17055 though and thus the confusion. :)

**Comment by TomasRoj** [comment]
Nice 😂 then please contact the original author to merge this.

**Pull request merged**
